# Generated by Django 5.0.4 on 2024-06-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="apis.school"
            ),
            preserve_default=False,
        ),
    ]
