# Generated by Django 5.0.4 on 2024-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_alter_classroom_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="classrooms",
            field=models.ManyToManyField(related_name="teachers", to="apis.classroom"),
        ),
    ]
