# Generated by Django 5.0.4 on 2024-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_alter_teacher_classrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "M"), ("female", "F")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("male", "M"), ("female", "F")], max_length=10
            ),
        ),
    ]
